/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\my-study\\lin2x\\Vue\\Vue2\\vuepress\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-10bfe02b",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-10bfe02b").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-5dedc36b",
    path: "/bar/four.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5dedc36b").then(next)
    },
  },
  {
    name: "v-7375187c",
    path: "/bar/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7375187c").then(next)
    },
  },
  {
    path: "/bar/index.html",
    redirect: "/bar/"
  },
  {
    name: "v-27b77d43",
    path: "/bar/three.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-27b77d43").then(next)
    },
  },
  {
    name: "v-79ed91ba",
    path: "/foo/one.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-79ed91ba").then(next)
    },
  },
  {
    name: "v-68a1aa3a",
    path: "/foo/two.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-68a1aa3a").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]